// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/labassistant.proto

package labassistantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Privilege int32

const (
	Privilege_PRIVILEGE_UNSPECIFIED Privilege = 0
	Privilege_PRIVILEGE_NONE        Privilege = 1
	Privilege_PRIVILEGE_ELEVATED    Privilege = 2
)

// Enum value maps for Privilege.
var (
	Privilege_name = map[int32]string{
		0: "PRIVILEGE_UNSPECIFIED",
		1: "PRIVILEGE_NONE",
		2: "PRIVILEGE_ELEVATED",
	}
	Privilege_value = map[string]int32{
		"PRIVILEGE_UNSPECIFIED": 0,
		"PRIVILEGE_NONE":        1,
		"PRIVILEGE_ELEVATED":    2,
	}
)

func (x Privilege) Enum() *Privilege {
	p := new(Privilege)
	*p = x
	return p
}

func (x Privilege) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Privilege) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_labassistant_proto_enumTypes[0].Descriptor()
}

func (Privilege) Type() protoreflect.EnumType {
	return &file_v1_labassistant_proto_enumTypes[0]
}

func (x Privilege) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Privilege.Descriptor instead.
func (Privilege) EnumDescriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{0}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_LOG         EventKind = 1
	EventKind_EVENT_KIND_PROGRESS    EventKind = 2
	EventKind_EVENT_KIND_STATE       EventKind = 3
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_LOG",
		2: "EVENT_KIND_PROGRESS",
		3: "EVENT_KIND_STATE",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_LOG":         1,
		"EVENT_KIND_PROGRESS":    2,
		"EVENT_KIND_STATE":       3,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_labassistant_proto_enumTypes[1].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_v1_labassistant_proto_enumTypes[1]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{1}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_QUEUED      JobState = 1
	JobState_JOB_STATE_RUNNING     JobState = 2
	JobState_JOB_STATE_SUCCEEDED   JobState = 3
	JobState_JOB_STATE_FAILED      JobState = 4
	JobState_JOB_STATE_TIMED_OUT   JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_QUEUED",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_SUCCEEDED",
		4: "JOB_STATE_FAILED",
		5: "JOB_STATE_TIMED_OUT",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_QUEUED":      1,
		"JOB_STATE_RUNNING":     2,
		"JOB_STATE_SUCCEEDED":   3,
		"JOB_STATE_FAILED":      4,
		"JOB_STATE_TIMED_OUT":   5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_labassistant_proto_enumTypes[2].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_v1_labassistant_proto_enumTypes[2]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{2}
}

// AssociateMessage is anything the associate sends up the stream.
type AssociateMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AssociateMessage_Hello
	//	*AssociateMessage_Heartbeat
	//	*AssociateMessage_Status
	//	*AssociateMessage_JobEvent
	//	*AssociateMessage_JobResult
	//	*AssociateMessage_LogChunk
	//	*AssociateMessage_Ack
	Payload       isAssociateMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateMessage) Reset() {
	*x = AssociateMessage{}
	mi := &file_v1_labassistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateMessage) ProtoMessage() {}

func (x *AssociateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateMessage.ProtoReflect.Descriptor instead.
func (*AssociateMessage) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{0}
}

func (x *AssociateMessage) GetPayload() isAssociateMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AssociateMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AssociateMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AssociateMessage) GetStatus() *StatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *AssociateMessage) GetJobEvent() *JobEvent {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_JobEvent); ok {
			return x.JobEvent
		}
	}
	return nil
}

func (x *AssociateMessage) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AssociateMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

func (x *AssociateMessage) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Payload.(*AssociateMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAssociateMessage_Payload interface {
	isAssociateMessage_Payload()
}

type AssociateMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AssociateMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AssociateMessage_Status struct {
	Status *StatusUpdate `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

type AssociateMessage_JobEvent struct {
	JobEvent *JobEvent `protobuf:"bytes,4,opt,name=job_event,json=jobEvent,proto3,oneof"`
}

type AssociateMessage_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,5,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type AssociateMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,6,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

type AssociateMessage_Ack struct {
	Ack *CommandAck `protobuf:"bytes,7,opt,name=ack,proto3,oneof"`
}

func (*AssociateMessage_Hello) isAssociateMessage_Payload() {}

func (*AssociateMessage_Heartbeat) isAssociateMessage_Payload() {}

func (*AssociateMessage_Status) isAssociateMessage_Payload() {}

func (*AssociateMessage_JobEvent) isAssociateMessage_Payload() {}

func (*AssociateMessage_JobResult) isAssociateMessage_Payload() {}

func (*AssociateMessage_LogChunk) isAssociateMessage_Payload() {}

func (*AssociateMessage_Ack) isAssociateMessage_Payload() {}

// ManagerMessage is anything the manager sends down the stream.
type ManagerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ManagerMessage_HelloAck
	//	*ManagerMessage_Command
	//	*ManagerMessage_Cancel
	//	*ManagerMessage_LogRequest
	//	*ManagerMessage_StatusRequest
	//	*ManagerMessage_RotateCert
	Payload       isManagerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerMessage) Reset() {
	*x = ManagerMessage{}
	mi := &file_v1_labassistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerMessage) ProtoMessage() {}

func (x *ManagerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerMessage.ProtoReflect.Descriptor instead.
func (*ManagerMessage) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerMessage) GetPayload() isManagerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ManagerMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ManagerMessage) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ManagerMessage) GetCancel() *CancelJob {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ManagerMessage) GetLogRequest() *LogStreamRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_LogRequest); ok {
			return x.LogRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

func (x *ManagerMessage) GetRotateCert() *RotateCert {
	if x != nil {
		if x, ok := x.Payload.(*ManagerMessage_RotateCert); ok {
			return x.RotateCert
		}
	}
	return nil
}

type isManagerMessage_Payload interface {
	isManagerMessage_Payload()
}

type ManagerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ManagerMessage_Command struct {
	Command *Command `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

type ManagerMessage_Cancel struct {
	Cancel *CancelJob `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type ManagerMessage_LogRequest struct {
	LogRequest *LogStreamRequest `protobuf:"bytes,4,opt,name=log_request,json=logRequest,proto3,oneof"`
}

type ManagerMessage_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,5,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type ManagerMessage_RotateCert struct {
	RotateCert *RotateCert `protobuf:"bytes,6,opt,name=rotate_cert,json=rotateCert,proto3,oneof"`
}

func (*ManagerMessage_HelloAck) isManagerMessage_Payload() {}

func (*ManagerMessage_Command) isManagerMessage_Payload() {}

func (*ManagerMessage_Cancel) isManagerMessage_Payload() {}

func (*ManagerMessage_LogRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_StatusRequest) isManagerMessage_Payload() {}

func (*ManagerMessage_RotateCert) isManagerMessage_Payload() {}

// RotateCert delivers a freshly issued client certificate; the associate persists it and
// reconnects using the new identity. The pinned CA is unchanged.
type RotateCert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       []byte                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        []byte                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCert) Reset() {
	*x = RotateCert{}
	mi := &file_v1_labassistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCert) ProtoMessage() {}

func (x *RotateCert) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCert.ProtoReflect.Descriptor instead.
func (*RotateCert) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{2}
}

func (x *RotateCert) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *RotateCert) GetKeyPem() []byte {
	if x != nil {
		return x.KeyPem
	}
	return nil
}

// Hello is the first frame the associate sends after the mTLS stream opens.
type Hello struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // for quartermaster version negotiation
	HostId           string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                             // identity; must match the mTLS client cert
	AssociateVersion string                 `protobuf:"bytes,3,opt,name=associate_version,json=associateVersion,proto3" json:"associate_version,omitempty"`
	Modules          []*ModuleInfo          `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"` // manifests + detection at connect time
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_v1_labassistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Hello) GetAssociateVersion() string {
	if x != nil {
		return x.AssociateVersion
	}
	return ""
}

func (x *Hello) GetModules() []*ModuleInfo {
	if x != nil {
		return x.Modules
	}
	return nil
}

type HelloAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // version the manager will speak
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                         // reason when accepted == false
	ServerTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_v1_labassistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{4}
}

func (x *HelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // manager-issued; idempotency key
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Params        []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // JSON, validated against ActionSpec.params_schema
	Timeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_v1_labassistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Command) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Command) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_v1_labassistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LogStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Stop          bool                   `protobuf:"varint,2,opt,name=stop,proto3" json:"stop,omitempty"`    // true to stop an existing stream
	Module        string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"` // e.g. "duo" or "sys"
	Params        []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // module-defined (container name, unit, follow, ...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamRequest) Reset() {
	*x = LogStreamRequest{}
	mi := &file_v1_labassistant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamRequest) ProtoMessage() {}

func (x *LogStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamRequest.ProtoReflect.Descriptor instead.
func (*LogStreamRequest) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{7}
}

func (x *LogStreamRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogStreamRequest) GetStop() bool {
	if x != nil {
		return x.Stop
	}
	return false
}

func (x *LogStreamRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *LogStreamRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"` // empty = all modules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_v1_labassistant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{8}
}

func (x *StatusRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Health        *HostHealth            `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_v1_labassistant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Heartbeat) GetHealth() *HostHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type HostHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float64                `protobuf:"fixed64,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Disks         []*DiskUsage           `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostHealth) Reset() {
	*x = HostHealth{}
	mi := &file_v1_labassistant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostHealth) ProtoMessage() {}

func (x *HostHealth) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostHealth.ProtoReflect.Descriptor instead.
func (*HostHealth) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{10}
}

func (x *HostHealth) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HostHealth) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *HostHealth) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HostHealth) GetDisks() []*DiskUsage {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     uint64                 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskUsage) Reset() {
	*x = DiskUsage{}
	mi := &file_v1_labassistant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskUsage) ProtoMessage() {}

func (x *DiskUsage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskUsage.ProtoReflect.Descriptor instead.
func (*DiskUsage) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{11}
}

func (x *DiskUsage) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *DiskUsage) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DiskUsage) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type StatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // JSON, described by the module's manifest
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_v1_labassistant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{12}
}

func (x *StatusUpdate) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *StatusUpdate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StatusUpdate) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	RejectReason  string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // set when a duplicate/invalid command is refused
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_v1_labassistant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{13}
}

func (x *CommandAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommandAck) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *CommandAck) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type JobEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Kind          EventKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=labassistant.v1.EventKind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Progress      float64                `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`                        // 0.0-1.0 when kind == EVENT_KIND_PROGRESS
	State         JobState               `protobuf:"varint,5,opt,name=state,proto3,enum=labassistant.v1.JobState" json:"state,omitempty"` // set when kind == EVENT_KIND_STATE
	At            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_v1_labassistant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{14}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *JobEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobEvent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobEvent) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=labassistant.v1.JobState" json:"state,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON, described by ActionSpec.result_schema
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_v1_labassistant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{15}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_v1_labassistant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{16}
}

func (x *LogChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type ModuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Actions       []*ActionSpec          `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Detection     *Detection             `protobuf:"bytes,5,opt,name=detection,proto3" json:"detection,omitempty"`
	ConfigSchema  []byte                 `protobuf:"bytes,6,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"` // JSON Schema for module-level per-host config (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_v1_labassistant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{17}
}

func (x *ModuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleInfo) GetActions() []*ActionSpec {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ModuleInfo) GetDetection() *Detection {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *ModuleInfo) GetConfigSchema() []byte {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

type ActionSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParamsSchema   []byte                 `protobuf:"bytes,3,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"` // JSON Schema
	ResultSchema   []byte                 `protobuf:"bytes,4,opt,name=result_schema,json=resultSchema,proto3" json:"result_schema,omitempty"` // JSON Schema
	Privilege      Privilege              `protobuf:"varint,5,opt,name=privilege,proto3,enum=labassistant.v1.Privilege" json:"privilege,omitempty"`
	Destructive    bool                   `protobuf:"varint,6,opt,name=destructive,proto3" json:"destructive,omitempty"`
	DefaultTimeout *durationpb.Duration   `protobuf:"bytes,7,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"`
	Streams        bool                   `protobuf:"varint,8,opt,name=streams,proto3" json:"streams,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionSpec) Reset() {
	*x = ActionSpec{}
	mi := &file_v1_labassistant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSpec) ProtoMessage() {}

func (x *ActionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSpec.ProtoReflect.Descriptor instead.
func (*ActionSpec) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{18}
}

func (x *ActionSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionSpec) GetParamsSchema() []byte {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

func (x *ActionSpec) GetResultSchema() []byte {
	if x != nil {
		return x.ResultSchema
	}
	return nil
}

func (x *ActionSpec) GetPrivilege() Privilege {
	if x != nil {
		return x.Privilege
	}
	return Privilege_PRIVILEGE_UNSPECIFIED
}

func (x *ActionSpec) GetDestructive() bool {
	if x != nil {
		return x.Destructive
	}
	return false
}

func (x *ActionSpec) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *ActionSpec) GetStreams() bool {
	if x != nil {
		return x.Streams
	}
	return false
}

type Detection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applicable    bool                   `protobuf:"varint,1,opt,name=applicable,proto3" json:"applicable,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g. {"distro": "debian", "orchestrator": "compose"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_v1_labassistant_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_v1_labassistant_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_v1_labassistant_proto_rawDescGZIP(), []int{19}
}

func (x *Detection) GetApplicable() bool {
	if x != nil {
		return x.Applicable
	}
	return false
}

func (x *Detection) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_v1_labassistant_proto protoreflect.FileDescriptor

const file_v1_labassistant_proto_rawDesc = "" +
	"\n" +
	"\x15v1/labassistant.proto\x12\x0flabassistant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xa4\x03\n" +
	"\x10AssociateMessage\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.labassistant.v1.HelloH\x00R\x05hello\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.labassistant.v1.HeartbeatH\x00R\theartbeat\x127\n" +
	"\x06status\x18\x03 \x01(\v2\x1d.labassistant.v1.StatusUpdateH\x00R\x06status\x128\n" +
	"\tjob_event\x18\x04 \x01(\v2\x19.labassistant.v1.JobEventH\x00R\bjobEvent\x12;\n" +
	"\n" +
	"job_result\x18\x05 \x01(\v2\x1a.labassistant.v1.JobResultH\x00R\tjobResult\x128\n" +
	"\tlog_chunk\x18\x06 \x01(\v2\x19.labassistant.v1.LogChunkH\x00R\blogChunk\x12/\n" +
	"\x03ack\x18\a \x01(\v2\x1b.labassistant.v1.CommandAckH\x00R\x03ackB\t\n" +
	"\apayload\"\x90\x03\n" +
	"\x0eManagerMessage\x128\n" +
	"\thello_ack\x18\x01 \x01(\v2\x19.labassistant.v1.HelloAckH\x00R\bhelloAck\x124\n" +
	"\acommand\x18\x02 \x01(\v2\x18.labassistant.v1.CommandH\x00R\acommand\x124\n" +
	"\x06cancel\x18\x03 \x01(\v2\x1a.labassistant.v1.CancelJobH\x00R\x06cancel\x12D\n" +
	"\vlog_request\x18\x04 \x01(\v2!.labassistant.v1.LogStreamRequestH\x00R\n" +
	"logRequest\x12G\n" +
	"\x0estatus_request\x18\x05 \x01(\v2\x1e.labassistant.v1.StatusRequestH\x00R\rstatusRequest\x12>\n" +
	"\vrotate_cert\x18\x06 \x01(\v2\x1b.labassistant.v1.RotateCertH\x00R\n" +
	"rotateCertB\t\n" +
	"\apayload\"@\n" +
	"\n" +
	"RotateCert\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\fR\x06keyPem\"\xaf\x01\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12+\n" +
	"\x11associate_version\x18\x03 \x01(\tR\x10associateVersion\x125\n" +
	"\amodules\x18\x04 \x03(\v2\x1b.labassistant.v1.ModuleInfoR\amodules\"\xa8\x01\n" +
	"\bHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12;\n" +
	"\vserver_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\x9d\x01\n" +
	"\aCommand\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\"\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"s\n" +
	"\x10LogStreamRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04stop\x18\x02 \x01(\bR\x04stop\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\"'\n" +
	"\rStatusRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\"u\n" +
	"\tHeartbeat\x123\n" +
	"\asent_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x123\n" +
	"\x06health\x18\x02 \x01(\v2\x1b.labassistant.v1.HostHealthR\x06health\"\xa7\x01\n" +
	"\n" +
	"HostHealth\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x01R\n" +
	"memPercent\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x04R\ruptimeSeconds\x120\n" +
	"\x05disks\x18\x04 \x03(\v2\x1a.labassistant.v1.DiskUsageR\x05disks\"a\n" +
	"\tDiskUsage\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x03 \x01(\x04R\tusedBytes\"w\n" +
	"\fStatusUpdate\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"`\n" +
	"\n" +
	"CommandAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"\xe4\x01\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.labassistant.v1.EventKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x01R\bprogress\x12/\n" +
	"\x05state\x18\x05 \x01(\x0e2\x19.labassistant.v1.JobStateR\x05state\x12*\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"}\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12/\n" +
	"\x05state\x18\x02 \x01(\x0e2\x19.labassistant.v1.JobStateR\x05state\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"M\n" +
	"\bLogChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"\xf2\x01\n" +
	"\n" +
	"ModuleInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\aactions\x18\x04 \x03(\v2\x1b.labassistant.v1.ActionSpecR\aactions\x128\n" +
	"\tdetection\x18\x05 \x01(\v2\x1a.labassistant.v1.DetectionR\tdetection\x12#\n" +
	"\rconfig_schema\x18\x06 \x01(\fR\fconfigSchema\"\xc6\x02\n" +
	"\n" +
	"ActionSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rparams_schema\x18\x03 \x01(\fR\fparamsSchema\x12#\n" +
	"\rresult_schema\x18\x04 \x01(\fR\fresultSchema\x128\n" +
	"\tprivilege\x18\x05 \x01(\x0e2\x1a.labassistant.v1.PrivilegeR\tprivilege\x12 \n" +
	"\vdestructive\x18\x06 \x01(\bR\vdestructive\x12B\n" +
	"\x0fdefault_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0edefaultTimeout\x12\x18\n" +
	"\astreams\x18\b \x01(\bR\astreams\"\xbe\x01\n" +
	"\tDetection\x12\x1e\n" +
	"\n" +
	"applicable\x18\x01 \x01(\bR\n" +
	"applicable\x12P\n" +
	"\fcapabilities\x18\x02 \x03(\v2,.labassistant.v1.Detection.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*R\n" +
	"\tPrivilege\x12\x19\n" +
	"\x15PRIVILEGE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePRIVILEGE_NONE\x10\x01\x12\x16\n" +
	"\x12PRIVILEGE_ELEVATED\x10\x02*j\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_KIND_LOG\x10\x01\x12\x17\n" +
	"\x13EVENT_KIND_PROGRESS\x10\x02\x12\x14\n" +
	"\x10EVENT_KIND_STATE\x10\x03*\x9a\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JOB_STATE_QUEUED\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x04\x12\x17\n" +
	"\x13JOB_STATE_TIMED_OUT\x10\x052c\n" +
	"\x0eManagerService\x12Q\n" +
	"\aConnect\x12!.labassistant.v1.AssociateMessage\x1a\x1f.labassistant.v1.ManagerMessage(\x010\x01B=Z;github.com/thinkaliker/labassistant/proto/v1;labassistantv1b\x06proto3"

var (
	file_v1_labassistant_proto_rawDescOnce sync.Once
	file_v1_labassistant_proto_rawDescData []byte
)

func file_v1_labassistant_proto_rawDescGZIP() []byte {
	file_v1_labassistant_proto_rawDescOnce.Do(func() {
		file_v1_labassistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_labassistant_proto_rawDesc), len(file_v1_labassistant_proto_rawDesc)))
	})
	return file_v1_labassistant_proto_rawDescData
}

var file_v1_labassistant_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_v1_labassistant_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_labassistant_proto_goTypes = []any{
	(Privilege)(0),                // 0: labassistant.v1.Privilege
	(EventKind)(0),                // 1: labassistant.v1.EventKind
	(JobState)(0),                 // 2: labassistant.v1.JobState
	(*AssociateMessage)(nil),      // 3: labassistant.v1.AssociateMessage
	(*ManagerMessage)(nil),        // 4: labassistant.v1.ManagerMessage
	(*RotateCert)(nil),            // 5: labassistant.v1.RotateCert
	(*Hello)(nil),                 // 6: labassistant.v1.Hello
	(*HelloAck)(nil),              // 7: labassistant.v1.HelloAck
	(*Command)(nil),               // 8: labassistant.v1.Command
	(*CancelJob)(nil),             // 9: labassistant.v1.CancelJob
	(*LogStreamRequest)(nil),      // 10: labassistant.v1.LogStreamRequest
	(*StatusRequest)(nil),         // 11: labassistant.v1.StatusRequest
	(*Heartbeat)(nil),             // 12: labassistant.v1.Heartbeat
	(*HostHealth)(nil),            // 13: labassistant.v1.HostHealth
	(*DiskUsage)(nil),             // 14: labassistant.v1.DiskUsage
	(*StatusUpdate)(nil),          // 15: labassistant.v1.StatusUpdate
	(*CommandAck)(nil),            // 16: labassistant.v1.CommandAck
	(*JobEvent)(nil),              // 17: labassistant.v1.JobEvent
	(*JobResult)(nil),             // 18: labassistant.v1.JobResult
	(*LogChunk)(nil),              // 19: labassistant.v1.LogChunk
	(*ModuleInfo)(nil),            // 20: labassistant.v1.ModuleInfo
	(*ActionSpec)(nil),            // 21: labassistant.v1.ActionSpec
	(*Detection)(nil),             // 22: labassistant.v1.Detection
	nil,                           // 23: labassistant.v1.Detection.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 25: google.protobuf.Duration
}
var file_v1_labassistant_proto_depIdxs = []int32{
	6,  // 0: labassistant.v1.AssociateMessage.hello:type_name -> labassistant.v1.Hello
	12, // 1: labassistant.v1.AssociateMessage.heartbeat:type_name -> labassistant.v1.Heartbeat
	15, // 2: labassistant.v1.AssociateMessage.status:type_name -> labassistant.v1.StatusUpdate
	17, // 3: labassistant.v1.AssociateMessage.job_event:type_name -> labassistant.v1.JobEvent
	18, // 4: labassistant.v1.AssociateMessage.job_result:type_name -> labassistant.v1.JobResult
	19, // 5: labassistant.v1.AssociateMessage.log_chunk:type_name -> labassistant.v1.LogChunk
	16, // 6: labassistant.v1.AssociateMessage.ack:type_name -> labassistant.v1.CommandAck
	7,  // 7: labassistant.v1.ManagerMessage.hello_ack:type_name -> labassistant.v1.HelloAck
	8,  // 8: labassistant.v1.ManagerMessage.command:type_name -> labassistant.v1.Command
	9,  // 9: labassistant.v1.ManagerMessage.cancel:type_name -> labassistant.v1.CancelJob
	10, // 10: labassistant.v1.ManagerMessage.log_request:type_name -> labassistant.v1.LogStreamRequest
	11, // 11: labassistant.v1.ManagerMessage.status_request:type_name -> labassistant.v1.StatusRequest
	5,  // 12: labassistant.v1.ManagerMessage.rotate_cert:type_name -> labassistant.v1.RotateCert
	20, // 13: labassistant.v1.Hello.modules:type_name -> labassistant.v1.ModuleInfo
	24, // 14: labassistant.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	25, // 15: labassistant.v1.Command.timeout:type_name -> google.protobuf.Duration
	24, // 16: labassistant.v1.Heartbeat.sent_at:type_name -> google.protobuf.Timestamp
	13, // 17: labassistant.v1.Heartbeat.health:type_name -> labassistant.v1.HostHealth
	14, // 18: labassistant.v1.HostHealth.disks:type_name -> labassistant.v1.DiskUsage
	24, // 19: labassistant.v1.StatusUpdate.observed_at:type_name -> google.protobuf.Timestamp
	1,  // 20: labassistant.v1.JobEvent.kind:type_name -> labassistant.v1.EventKind
	2,  // 21: labassistant.v1.JobEvent.state:type_name -> labassistant.v1.JobState
	24, // 22: labassistant.v1.JobEvent.at:type_name -> google.protobuf.Timestamp
	2,  // 23: labassistant.v1.JobResult.state:type_name -> labassistant.v1.JobState
	21, // 24: labassistant.v1.ModuleInfo.actions:type_name -> labassistant.v1.ActionSpec
	22, // 25: labassistant.v1.ModuleInfo.detection:type_name -> labassistant.v1.Detection
	0,  // 26: labassistant.v1.ActionSpec.privilege:type_name -> labassistant.v1.Privilege
	25, // 27: labassistant.v1.ActionSpec.default_timeout:type_name -> google.protobuf.Duration
	23, // 28: labassistant.v1.Detection.capabilities:type_name -> labassistant.v1.Detection.CapabilitiesEntry
	3,  // 29: labassistant.v1.ManagerService.Connect:input_type -> labassistant.v1.AssociateMessage
	4,  // 30: labassistant.v1.ManagerService.Connect:output_type -> labassistant.v1.ManagerMessage
	30, // [30:31] is the sub-list for method output_type
	29, // [29:30] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_v1_labassistant_proto_init() }
func file_v1_labassistant_proto_init() {
	if File_v1_labassistant_proto != nil {
		return
	}
	file_v1_labassistant_proto_msgTypes[0].OneofWrappers = []any{
		(*AssociateMessage_Hello)(nil),
		(*AssociateMessage_Heartbeat)(nil),
		(*AssociateMessage_Status)(nil),
		(*AssociateMessage_JobEvent)(nil),
		(*AssociateMessage_JobResult)(nil),
		(*AssociateMessage_LogChunk)(nil),
		(*AssociateMessage_Ack)(nil),
	}
	file_v1_labassistant_proto_msgTypes[1].OneofWrappers = []any{
		(*ManagerMessage_HelloAck)(nil),
		(*ManagerMessage_Command)(nil),
		(*ManagerMessage_Cancel)(nil),
		(*ManagerMessage_LogRequest)(nil),
		(*ManagerMessage_StatusRequest)(nil),
		(*ManagerMessage_RotateCert)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_labassistant_proto_rawDesc), len(file_v1_labassistant_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_labassistant_proto_goTypes,
		DependencyIndexes: file_v1_labassistant_proto_depIdxs,
		EnumInfos:         file_v1_labassistant_proto_enumTypes,
		MessageInfos:      file_v1_labassistant_proto_msgTypes,
	}.Build()
	File_v1_labassistant_proto = out.File
	file_v1_labassistant_proto_goTypes = nil
	file_v1_labassistant_proto_depIdxs = nil
}
